import { FunctionKeys, NonFunctionKeys } from 'utility-types';

export const WebGLRenderingContextMethods: FunctionKeys<WebGLRenderingContext>[] = [
  'activeTexture',
  'attachShader',
  'bindAttribLocation',
  'bindBuffer',
  'bindFramebuffer',
  'bindRenderbuffer',
  'bindTexture',
  'blendColor',
  'blendEquation',
  'blendEquationSeparate',
  'blendFunc',
  'blendFuncSeparate',
  'bufferData',
  'bufferSubData',
  'checkFramebufferStatus',
  'clear',
  'clearColor',
  'clearDepth',
  'clearStencil',
  'colorMask',
  'compileShader',
  // 'compressedTexImage[23]D',
  'compressedTexImage2D',
  'compressedTexSubImage2D',
  'copyTexImage2D',
  'copyTexSubImage2D',
  'createBuffer',
  'createFramebuffer',
  'createProgram',
  'createRenderbuffer',
  'createShader',
  'createTexture',
  'cullFace',
  'deleteBuffer',
  'deleteFramebuffer',
  'deleteProgram',
  'deleteRenderbuffer',
  'deleteShader',
  'deleteTexture',
  'depthFunc',
  'depthMask',
  'depthRange',
  'detachShader',
  'disable',
  'disableVertexAttribArray',
  'drawArrays',
  'drawElements',
  'enable',
  'enableVertexAttribArray',
  'finish',
  'flush',
  'framebufferRenderbuffer',
  'framebufferTexture2D',
  'frontFace',
  'generateMipmap',
  'getActiveAttrib',
  'getActiveUniform',
  'getAttachedShaders',
  'getAttribLocation',
  'getBufferParameter',
  'getContextAttributes',
  'getError',
  'getExtension',
  'getFramebufferAttachmentParameter',
  'getParameter',
  'getProgramInfoLog',
  'getProgramParameter',
  'getRenderbufferParameter',
  'getShaderInfoLog',
  'getShaderParameter',
  'getShaderPrecisionFormat',
  'getShaderSource',
  'getSupportedExtensions',
  'getTexParameter',
  'getUniform',
  'getUniformLocation',
  'getVertexAttrib',
  'getVertexAttribOffset',
  'hint',
  'isBuffer',
  'isContextLost',
  'isEnabled',
  'isFramebuffer',
  'isProgram',
  'isRenderbuffer',
  'isShader',
  'isTexture',
  'lineWidth',
  'linkProgram',
  // 'makeXRCompatibl',
  'pixelStorei',
  'polygonOffset',
  'readPixels',
  'renderbufferStorage',
  'sampleCoverage',
  'scissor',
  'shaderSource',
  'stencilFunc',
  'stencilFuncSeparate',
  'stencilMask',
  'stencilMaskSeparate',
  'stencilOp',
  'stencilOpSeparate',
  'texImage2D',
  // 'texParameter[fi]',
  'texParameterf',
  'texParameteri',

  'texSubImage2D',

  // 'uniform[1234][fi][v]',
  'uniform1f',
  'uniform1fv',
  'uniform1i',
  'uniform1iv',
  'uniform2f',
  'uniform2fv',
  'uniform2i',
  'uniform2iv',
  'uniform3f',
  'uniform3fv',
  'uniform3i',
  'uniform3iv',
  'uniform4f',
  'uniform4fv',
  'uniform4i',
  'uniform4iv',

  // 'uniformMatrix[234]fv',
  'uniformMatrix2fv',
  'uniformMatrix3fv',
  'uniformMatrix4fv',

  'useProgram',
  'validateProgram',

  // 'vertexAttrib[1234]f[v]',
  'vertexAttrib1f',
  'vertexAttrib2f',
  'vertexAttrib3f',
  'vertexAttrib4f',

  'vertexAttribPointer',
  'viewport'
];

export const WebGLRenderingContextProperties: NonFunctionKeys<WebGLRenderingContext>[] = [
  'drawingBufferColorSpace'
];

export const WebGL2RenderingContextMethods: FunctionKeys<WebGL2RenderingContext>[] = [
  'beginQuery',
  'beginTransformFeedback',
  'bindBufferBase',
  'bindBufferRange',
  'bindSampler',
  'bindTransformFeedback',
  'bindVertexArray',
  'blitFramebuffer',
  // 'clearBuffer[fiuv]',
  'clearBufferfi',
  'clearBufferfv',
  'clearBufferiv',
  'clearBufferuiv',

  'clientWaitSync',
  'compressedTexSubImage3D',
  'copyBufferSubData',
  'copyTexSubImage3D',
  'createQuery',
  'createSampler',
  'createTransformFeedback',
  'createVertexArray',
  'deleteQuery',
  'deleteSampler',
  'deleteSync',
  'deleteTransformFeedback',
  'deleteVertexArray',
  'drawArraysInstanced',
  'drawBuffers',
  'drawElementsInstanced',
  'drawRangeElements',
  'endQuery',
  'endTransformFeedback',
  'fenceSync',
  'framebufferTextureLayer',
  'getActiveUniformBlockName',
  'getActiveUniformBlockParameter',
  'getActiveUniforms',
  'getBufferSubData',
  'getFragDataLocation',
  'getIndexedParameter',
  'getInternalformatParameter',
  'getQuery',
  'getQueryParameter',
  'getSamplerParameter',
  'getSyncParameter',
  'getTransformFeedbackVarying',
  'getUniformBlockIndex',
  'getUniformIndices',
  'invalidateFramebuffer',
  'invalidateSubFramebuffer',
  'isQuery',
  'isSampler',
  'isSync',
  'isTransformFeedback',
  'isVertexArray',
  'pauseTransformFeedback',
  'readBuffer',
  'renderbufferStorageMultisample',
  'resumeTransformFeedback',
  // 'samplerParameter[if]',
  'samplerParameteri',
  'samplerParameterf',

  'texImage3D',
  'texStorage2D',
  'texStorage3D',
  'texSubImage3D',
  'transformFeedbackVaryings',

  // 'uniform[1234][uif][v]',
  'uniform1f',
  'uniform1fv',
  'uniform1i',
  'uniform1iv',
  'uniform1ui',
  'uniform1uiv',

  'uniform2f',
  'uniform2fv',
  'uniform2i',
  'uniform2iv',
  'uniform2ui',
  'uniform2uiv',

  'uniform3f',
  'uniform3fv',
  'uniform3i',
  'uniform3iv',
  'uniform3ui',
  'uniform3uiv',

  'uniform4f',
  'uniform4fv',
  'uniform4i',
  'uniform4iv',
  'uniform4ui',
  'uniform4uiv',

  'uniformBlockBinding',

  // 'uniformMatrix[234]x[234]fv',
  'uniformMatrix2fv',
  'uniformMatrix2x3fv',
  'uniformMatrix2x4fv',

  'uniformMatrix3fv',
  'uniformMatrix3x2fv',
  'uniformMatrix3x4fv',

  'uniformMatrix4fv',
  'uniformMatrix4x2fv',
  'uniformMatrix4x3fv',

  'vertexAttribDivisor',

  // 'vertexAttribI4[u]i[v]',
  'vertexAttribI4i',
  'vertexAttribI4iv',
  'vertexAttribI4ui',
  'vertexAttribI4uiv',

  'vertexAttribIPointer',
  'waitSync'
];

export const WebGL2RenderingContextProperties: NonFunctionKeys<WebGL2RenderingContext>[] = [];
