import { NonFunctionKeys, FunctionKeys } from 'utility-types';

export const CanvasRenderingContext2DMethods: FunctionKeys<CanvasRenderingContext2D>[] = [
  'arc',
  'arcTo',
  'beginPath',
  'bezierCurveTo',
  'clearRect',
  'clip',
  'closePath',
  'createConicGradient',
  'createImageData',
  'createLinearGradient',
  'createPattern',
  'createRadialGradient',
  'drawFocusIfNeeded',
  'drawImage',
  'ellipse',
  'fill',
  'fillRect',
  'fillText',
  'getContextAttributes',
  'getImageData',
  'getLineDash',
  'getTransform',
  // 'isContextLost',
  'isPointInPath',
  'isPointInStroke',
  'lineTo',
  'measureText',
  'moveTo',
  'putImageData',
  'quadraticCurveTo',
  'rect',
  'reset',
  'resetTransform',
  'restore',
  'rotate',
  'roundRect',
  'save',
  'scale',
  // 'scrollPathIntoView',
  'setLineDash',
  'setTransform',
  'stroke',
  'strokeRect',
  'strokeText',
  'transform',
  'translate'
];

export const CanvasRenderingContext2DProperties: NonFunctionKeys<CanvasRenderingContext2D>[] = [
  'canvas',
  'direction',
  'fillStyle',
  'filter',
  'font',
  'fontKerning',
  // 'fontStretch',
  // 'fontVariantCaps',
  'globalAlpha',
  'globalCompositeOperation',
  'imageSmoothingEnabled',
  'imageSmoothingQuality',
  'lineCap',
  'lineDashOffset',
  'lineJoin',
  'lineWidth',
  'miterLimit',
  'shadowBlur',
  'shadowColor',
  'shadowOffsetX',
  'shadowOffsetY',
  'strokeStyle',
  'textAlign',
  'textBaseline'
  // 'textRendering',
  // 'wordSpacing'
];
